function cudaonlineide(){var O='bootstrap',P='begin',Q='gwt.codesvr.cudaonlineide=',R='gwt.codesvr=',S='cudaonlineide',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='Failed to load ',ob='head',pb='meta',qb='name',rb='cudaonlineide::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='cudaonlineide.nocache.js',Ib='base',Jb='//',Kb='gxt.user.agent',Lb='chrome',Mb='opera',Nb='msie',Ob=10,Pb='ie10',Qb=9,Rb='ie9',Sb=8,Tb='ie8',Ub='msie 7',Vb='ie7',Wb='msie 6',Xb='ie6',Yb='safari',Zb='version/3',$b='safari3',_b='version/4',ac='safari4',bc='safari5',cc='gecko',dc='rv:1.8',ec='gecko1_8',fc='gecko1_9',gc='adobeair',hc='air',ic=2,jc=3,kc=4,lc=5,mc=6,nc=7,oc='user.agent',pc='webkit',qc=11,rc='user.agent.os',sc='macintosh',tc='mac os x',uc='mac',vc='linux',wc='windows',xc='win32',yc='unknown',zc='selectingPermutation',Ac='cudaonlineide.devmode.js',Bc='07295DA559ACB4CF037DEE7D9BAF53DA',Cc=':1',Dc=':10',Ec=':11',Fc=':2',Gc=':3',Hc=':4',Ic=':5',Jc=':6',Kc=':7',Lc=':8',Mc=':9',Nc='23C477B65657A34CEE9F0F710377CE70',Oc='30FC71AEC0F29E5245D1F6E1787DFC3F',Pc='5BE54831395D169BD224CCBEED35D594',Qc='9305380BA95491160E26177E8C6EEF52',Rc='B2C5D682F72C0A25256C3E3A34826674',Sc='EE0828B3B1A7600CD98FF60C57269BD5',Tc=':',Uc='.cache.js',Vc='link',Wc='rel',Xc='stylesheet',Yc='href',Zc='loadExternalRefs',$c='reset.css',_c='end',ad='http:',bd='file:',cd='_gwt_dummy_',dd='__gwtDevModeHook:cudaonlineide',ed='Ignoring non-whitelisted Dev Mode URL: ',fd=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
cudaonlineide.__sendStats=r;cudaonlineide.__moduleName=S;cudaonlineide.__errFn=null;cudaonlineide.__moduleBase=U;cudaonlineide.__softPermutationId=V;cudaonlineide.__computePropValue=null;cudaonlineide.__getPropMap=null;cudaonlineide.__installRunAsyncCode=function(){};cudaonlineide.__gwtStartLoadingFragment=function(){return null};cudaonlineide.__gwt_isKnownPropertyValue=function(){return false};cudaonlineide.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};cudaonlineide.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[cudaonlineide.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
cudaonlineide.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(cudaonlineide.__errFn){n.onerror=function(){cudaonlineide.__errFn(S,new Error(nb+code))}}p.getElementsByTagName(ob)[V].appendChild(n)}
cudaonlineide.__startLoadingFragment=function(a){return D(a)};cudaonlineide.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,bb);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;cudaonlineide.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return cudaonlineide.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Kb]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Lb)!=-1)return Lb;if(a.indexOf(Mb)!=-1)return Mb;if(a.indexOf(Nb)!=-1){if(p.documentMode>=Ob)return Pb;if(p.documentMode>=Qb)return Rb;if(p.documentMode>=Sb)return Tb;if(a.indexOf(Ub)!=-1)return Vb;if(a.indexOf(Wb)!=-1)return Xb;return Pb}if(a.indexOf(Yb)!=-1){if(a.indexOf(Zb)!=-1)return $b;if(a.indexOf(_b)!=-1)return ac;return bc}if(a.indexOf(cc)!=-1){if(a.indexOf(dc)!=-1)return ec;return fc}if(a.indexOf(gc)!=-1)return hc;return null};i[Kb]={air:V,chrome:W,gecko1_8:ic,gecko1_9:jc,ie10:kc,ie8:lc,ie9:mc,safari3:nc,safari4:Sb,safari5:Qb};j[oc]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(pc)!=-1}())return Yb;if(function(){return a.indexOf(Nb)!=-1&&(b>=Ob&&b<qc)}())return Pb;if(function(){return a.indexOf(Nb)!=-1&&(b>=Qb&&b<qc)}())return Rb;if(function(){return a.indexOf(Nb)!=-1&&(b>=Sb&&b<qc)}())return Tb;if(function(){return a.indexOf(cc)!=-1||b>=qc}())return ec;return bb};i[oc]={gecko1_8:V,ie10:W,ie8:ic,ie9:jc,safari:kc};j[rc]=function(){var a=o.navigator.userAgent.toLowerCase();if(a.indexOf(sc)!=-1||a.indexOf(tc)!=-1){return uc}if(a.indexOf(vc)!=-1){return vc}if(a.indexOf(wc)!=-1||a.indexOf(xc)!=-1){return wc}return yc};i[rc]={linux:V,mac:W,unknown:ic,windows:jc};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};cudaonlineide.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};cudaonlineide.__computePropValue=k;o.__gwt_activeModules[S].bindings=cudaonlineide.__getPropMap;r(O,zc);if(q()){return D(Ac)}var l;try{h([hc,Yb,vc],Bc);h([hc,Yb,uc],Bc+Cc);h([bc,Yb,yc],Bc+Dc);h([bc,Yb,wc],Bc+Ec);h([hc,Yb,yc],Bc+Fc);h([hc,Yb,wc],Bc+Gc);h([Lb,Yb,vc],Bc+Hc);h([Lb,Yb,uc],Bc+Ic);h([Lb,Yb,yc],Bc+Jc);h([Lb,Yb,wc],Bc+Kc);h([bc,Yb,vc],Bc+Lc);h([bc,Yb,uc],Bc+Mc);h([ec,ec,vc],Nc);h([ec,ec,uc],Nc+Cc);h([ec,ec,yc],Nc+Fc);h([ec,ec,wc],Nc+Gc);h([Tb,Tb,vc],Oc);h([Tb,Tb,uc],Oc+Cc);h([Tb,Tb,yc],Oc+Fc);h([Tb,Tb,wc],Oc+Gc);h([fc,ec,vc],Pc);h([fc,ec,uc],Pc+Cc);h([fc,ec,yc],Pc+Fc);h([fc,ec,wc],Pc+Gc);h([Rb,Rb,vc],Qc);h([Rb,Rb,uc],Qc+Cc);h([Rb,Rb,yc],Qc+Fc);h([Rb,Rb,wc],Qc+Gc);h([Pb,Pb,vc],Rc);h([Pb,Pb,uc],Rc+Cc);h([Pb,Pb,yc],Rc+Fc);h([Pb,Pb,wc],Rc+Gc);h([$b,Yb,vc],Sc);h([$b,Yb,uc],Sc+Cc);h([$b,Yb,yc],Sc+Fc);h([$b,Yb,wc],Sc+Gc);h([ac,Yb,vc],Sc+Hc);h([ac,Yb,uc],Sc+Ic);h([ac,Yb,yc],Sc+Jc);h([ac,Yb,wc],Sc+Kc);l=f[k(Kb)][k(oc)][k(rc)];var m=l.indexOf(Tc);if(m!=-1){g=parseInt(l.substring(m+W),Ob);l=l.substring(V,m)}}catch(a){}cudaonlineide.__softPermutationId=g;return D(l+Uc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(Vc);b.setAttribute(Wc,Xc);b.setAttribute(Yc,D(a));p.getElementsByTagName(ob)[V].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(Zc,P);c($c);r(Zc,_c)}
B();cudaonlineide.__moduleBase=C();t[S].moduleBase=cudaonlineide.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==ad||o.location.protocol==bd);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=cd;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=dd;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(ed+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+fd]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,_c);A(H);return true}
cudaonlineide.succeeded=cudaonlineide();